const CARS_FETCH_BEGIN = 'CARS_FETCH_BEGIN'
const CARS_FETCH_END = 'CARS_FETCH_END'
const CARS_FETCH_FAIL = 'CARS_FETCH_FAIL'

const DEALERS_FETCH_BEGIN = 'DEALERS_FETCH_BEGIN'
const DEALERS_FETCH_END = 'DEALERS_FETCH_END'
const DEALERS_FETCH_FAIL = 'DEALERS_FETCH_FAIL'

export {
  CARS_FETCH_BEGIN,
  CARS_FETCH_END,
  CARS_FETCH_FAIL,
  DEALERS_FETCH_BEGIN,
  DEALERS_FETCH_END,
  DEALERS_FETCH_FAIL,
}
